url="http://0.0.0.0:8000"
logon=url+"/logon"
getstatus=url+"/getstatus"
getconfiguration=url+"/getconfiguration"
setconfiguration=url+"/setconfiguration"
setmaxpower=url+"/setmaxpower"
setsolarmode=url+"/setsolarmode"